Bids/urls.py
from django.urls import path 
from .views import reject_approval, BidsView,buy_car,update_payments,payment_done,payment_canceled, MyBidsView, AddBidView,BidDetailView,EditBidView,DeleteBidView

urlpatterns = [
    path('',BidsView.as_view(),name="bids"),
    path('<slug>',BidDetailView.as_view(),name="bid_details"),
    path('edit/<slug>',EditBidView.as_view(),name='edit_bid'),
    path('delete/<slug>',DeleteBidView.as_view(),name='delete_bid'),
    path('bid_car/<car_id>/',AddBidView.as_view(),name='bid_car'),
    path('my_bids/',MyBidsView.as_view(),name='my_bids'),
    path("<slug>/reject", reject_approval, name="reject_approval"),
    path('<slug>/process-payment/', buy_car, name='buy_car'),
    path('finish_payments/<slug>', update_payments, name='finish_payments'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
]

Cars/urls.py
from django.conf import settings
from django.urls import path
from .import views
from .views import  CarUserView,CarCategoryView, cancel_approval,approve_bid,CarBids,CarsView,MyCarsView,AddVehicleView,CarDetailView,DeleteVehicleView,EditVehicleView,AddFavouriteView,FavouritesView, approve_bid
from django.conf.urls.static import static
urlpatterns = [
    path('',CarsView.as_view(),name="cars"),

    path('add_car',AddVehicleView.as_view(),name="add_vehicles"),
    path('<slug>',CarDetailView.as_view(),name="vehicle_details"), 
    path('edit/<slug>',EditVehicleView.as_view(),name="edit_vehicle"), 
    path('delete/<slug>',DeleteVehicleView.as_view(),name="delete_vehicle"), 
    path('favourite/<slug>',AddFavouriteView,name="add_favourite"), 
    path('user/favourites/',FavouritesView.as_view(),name="favourites"),
    # path('<slug>',AddVehicleImagesView.as_view(),name="add_images"),   
    path('my_cars/',MyCarsView.as_view(),name="my_cars"),
    path('this_car_bids/<slug>',CarBids.as_view(),name='this_car_bids'),
    path("<slug>/approve", approve_bid, name="approve_bid"), 
    path('<slug>/cancel',cancel_approval,name="cancel_bid"),
      # path('<slug>',add_vehicle_image,name="add_imagess"),
    path('category/<slug>/',CarCategoryView,name='category'),
    path('user/<username>/',CarUserView,name='user_cars')
    
]

  
  

MotoCar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/',include('Cars.urls')),
    path('',include('Pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('Profiles.urls')),
    path('bids/', include('Bids.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
]
handler404 = 'Pages.views.error_404'
handler500 = 'Pages.views.error_500'
if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL,document_root =settings.STATIC_ROOT) 
  urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)
      

Cars/models.py
import datetime
from unicodedata import category
from Cars.choises import  car_models,fuel_type,body_type,transmission_type,drive_type,steering_type
from pyexpat import model
from autoslug import AutoSlugField
from django.db import models
from  ckeditor.fields import RichTextField
from django.core.validators import MaxValueValidator,MinValueValidator
from django.conf import settings
from django.forms import CharField, ValidationError
from django.urls import reverse
from hitcount.models import HitCountMixin
from django.template.defaultfilters import slugify
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.settings import MODEL_HITCOUNT
from django.contrib.auth.models import User
import random,string
from django.db.models.signals import pre_save 
from django.core.exceptions import ValidationError
from django_resized import ResizedImageField


class Category(models.Model): 

    name = models.CharField(choices=car_models,max_length=100)
    slug =AutoSlugField(populate_from='name',unique=True)
    description = RichTextField(blank=True,null=True)
    created_date =models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.name
    def get_absolute_url(self):
        return reverse("category",kwargs={'slug':self.slug})
    


def random_string_generator(size=10,chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def unique_stock_id_generator(instance):
    # code to get unique stock id
    new_stock_id =random_string_generator().upper()
    Klass = instance.__class__
    qs_exists =Klass.objects.filter(stock_id =new_stock_id).exists()
    if qs_exists:
        return unique_stock_id_generator(instance)
    return new_stock_id




def current_year():
        return datetime.datetime.now().year
def only_digit(value):
        if value.isdigit() == False:
            raise ValidationError('Only Digits Allowed')

def max_value_current_year(value):
        return MaxValueValidator(current_year())(value)


class Car(models.Model,HitCountMixin):
    Mombasa = 'Mombasa'
    Kwale= 'Kwale'
    Kilifi= 'Kilifi'
    TanaRiver= 'Tana River'
    Lamu= 'Lamu'
    TaitaTaveta= 'Taita-Taveta'
    Garissa ='Garissa'
    Wajir= 'Wajir'
    Mandera= 'Mandera'
    Marsabit= 'Marsabit'
    Isiolo= 'Isiolo'
    MERU= 'MERU'
    TharakaNithi= 'Tharaka-Nithi'
    Embu= 'Embu'
    Kitui ='Kitui'
    Machakos= 'Machakos'
    Makueni= 'Makueni'
    Nyandarua= 'Nyandarua'
    Nyeri= 'Nyeri'
    Kirinyaga='Kirinyaga'
    Muranga="Muranga"
    Kiambu= 'Kiambu'
    Turkana ='Turkana'
    WestPokot='West Pokot'
    Samburu= 'Samburu'
    TransNzoia ='Trans Nzoia'
    UasinGishu= 'Uasin Gishu'
    ElgeyoMarakwet= 'Elgeyo-Marakwet'
    Nandi ='Nandi'
    Baringo= 'Baringo'
    Laikipia ='Laikipia'
    Nakuru= 'Nakuru'
    Narok= 'Narok'
    Kajiado= 'Kajiado'
    Kericho= 'Kericho'
    Bomet= 'Bomet'
    Kakamega ='Kakamega'
    Vihiga= 'Vihiga'
    Bungoma= 'Bungoma'
    Busia= 'Busia'
    Siaya= 'Siaya'
    Kisumu ='Kisumu'
    HomaBay= 'Homa Bay'
    Migori= 'Migori'
    Kisii= 'Kisii'
    Nyamira= 'Nyamira'
    Nairobi= 'Nairobi'

    county= [
        (Mombasa, 'Mombasa'),
        (Kwale, 'Kwale'),
        (Kilifi, 'Kilifi'),
        (TanaRiver, 'Tana River'),
        (Lamu, 'Lamu'),
        (TaitaTaveta, 'Taita-Taveta'),
        (Garissa ,'Garissa'),
        (Wajir, 'Wajir'),
        (Mandera, 'Mandera'),
        (Marsabit, 'Marsabit'),
        (Isiolo, 'Isiolo'),
        (MERU, 'Meru'),
        (TharakaNithi, 'Tharaka-Nithi'),
        (Embu, 'Embu'),
        (Kitui ,'Kitui'),
        (Machakos, 'Machakos'),
        (Makueni, 'Makueni'),
        (Nyandarua, 'Nyandarua'),
        (Nyeri, 'Nyeri'),
        (Kirinyaga,'Kirinyaga'),
        (Muranga,"Murang'a"),
        (Kiambu, 'Kiambu'),
        (Turkana ,'Turkana'),
        (WestPokot,' West Pokot'),
        (Samburu, 'Samburu'),
        (TransNzoia ,'Trans Nzoia'),
        (UasinGishu, 'Uasin Gishu'),
        (ElgeyoMarakwet, 'Elgeyo-Marakwet'),
        (Nandi ,'Nandi'),
        (Baringo, 'Baringo'),
        (Laikipia ,'Laikipia'),
        (Nakuru, 'Nakuru'),
        (Narok, 'Narok'),
        (Kajiado, 'Kajiado'),
        (Kericho, 'Kericho'),
        (Bomet, 'Bomet'),
        (Kakamega ,'Kakamega'),
        (Vihiga, 'Vihiga'),
        (Bungoma, 'Bungoma'),
        (Busia, 'Busia'),
        (Siaya, 'Siaya'),
        (Kisumu ,'Kisumu'),
        (HomaBay, 'Homa Bay'),
        (Migori, 'Migori'),
        (Kisii, 'Kisii'),
        (Nyamira, 'Nyamira'),
        (Nairobi, 'Nairobi'),
    ]
    
   
    

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=False)
    stock_id = models.CharField(blank=True,max_length=30)
    category = models.ForeignKey(Category,verbose_name="Category",on_delete=models.CASCADE)
    slug =AutoSlugField(populate_from='car_name',unique=True)
    body_type = models.CharField(choices=body_type, max_length= 50)
    car_name = models.CharField(max_length=250)   
    transmission = models.CharField(choices=transmission_type, max_length= 50)
    drive = models.CharField(choices=drive_type, max_length= 50)
    engine_type = models.CharField(max_length=250)
    engine_size = models.CharField(max_length=250)
    fuel = models.CharField(choices=fuel_type, max_length= 50)
    color= models.CharField(max_length=250)

    steering= models.CharField(choices=steering_type, max_length=50)
    number_of_ownership= models.IntegerField(blank=True,null=True)
    imperfection= RichTextField(blank=True,null=True)
    platenumber= models.CharField(max_length=250)
    vehicle_weight = models.CharField(max_length=250,blank=True,null=True,validators=[only_digit])
    max_load_capacity = models.CharField(max_length=250,blank=True,null=True,validators=[only_digit])
    body_length = models.CharField(max_length=250,blank=True,null=True,validators=[only_digit])
    chasis_number = models.CharField(max_length=250)

    vendor_county = models.CharField(choices=county, max_length= 50)
    vendor_location = models.CharField(max_length=250)
    # vendor_address = models.CharField(max_length=250)
    year_of_make = models.PositiveIntegerField(default=current_year(),validators=[MinValueValidator(1984),max_value_current_year])
    mileage = models.CharField(max_length=250,validators=[only_digit])
    price =models.CharField(max_length=250,validators=[only_digit])
    status = models.CharField(max_length=250,blank=True,null=True,default="NOT SOLD")
    published = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False) 
    hit_count_generic =GenericRelation(MODEL_HITCOUNT,object_id_field='object_pk',related_query_name='hit_count_generic_relation')   
    created_date = models.DateTimeField(auto_now_add=True)
    favourites = models.ManyToManyField(User,related_name='favourites',default=None,blank=True)

    # accesories      
    air_bag =  models.BooleanField(max_length = 50,default=False)
    # dual_air_bag =  models.BooleanField(max_length = 50,default=False)    
    grill_guard = models.BooleanField(max_length = 50,default=False)
    power_steerring = models.BooleanField(max_length = 50,default=False)
    sun_roof =  models.BooleanField(max_length = 50,default=False)
    navigation =  models.BooleanField(max_length = 50,default=False)
    rear_spoiler = models.BooleanField(max_length = 50,default=False)
    power_windows =  models.BooleanField(max_length = 50,default=False)
    leather_seats=  models.BooleanField(max_length = 50,default=False)
    roof_rails=  models.BooleanField(max_length = 50,default=False)
    dual_air_bags =  models.BooleanField(max_length = 50,default=False) 
    fog_lights =  models.BooleanField(max_length = 50,default=False)
    back_tire =  models.BooleanField(max_length = 50,default=False)
    alloy_wheels =  models.BooleanField(max_length = 50,default=False)
    air_conditioner =  models.BooleanField(max_length = 50,default=False)
    anti_lock_brake_system =  models.BooleanField(max_length = 50,default=False)

   


    # class Meta:
        # ordering = 'descending',
    def __str__(self):
        return self.car_name
    def get_absolute_url(self):
        return reverse("vehicle_details",kwargs={'slug':self.slug})
    
    # def get_related_vehicle_by_category(self):
    #     return Car.objects.filter(category_id=self.category_id)
    #     # .exclude(pk=self.pk).order_by('-created_date')[:8]
   
# ,tag_id =self.tag_id

def pre_save_stock_id(sender,instance,*args,**kwargs):
        if not instance.stock_id:
            instance.stock_id =unique_stock_id_generator(instance)
pre_save.connect(pre_save_stock_id,sender=Car)

   
    
   

class CarImages(models.Model):
    car = models.ForeignKey(Car, verbose_name='Car_images',on_delete=models.CASCADE)
    image =ResizedImageField(quality=90,upload_to='cars/car_images/')
    created_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("cars")

    @property 
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url 
    

templates/cars/cars.html
{% extends 'base.html' %}
{% block title %} Vehicles {% endblock %}
{% block content %}
{% load static %}
{% load hitcount_tags %}
{% load crispy_forms_tags %}
{% load popular_vehicles%}
{% load humanize %}

{% comment %} {% load humanize %} {% endcomment %}
<main id="main"> 
  <br>
  

<section class="breadcrumbs">
    
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Vehicles</h2>
      <ol>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li>Vehicles</li>
      </ol>
    </div>

  </div>
</section><!-- Job breadcrumbs Section --> 

{% include 'includes/profile_message.html'%}

<section class="vehicles" id="vehicles">
    <div class="container-fluid">
        <div class="row">

          <div class="col-md-9 col-sm-12">

            <div class="row">
           

    {% comment %} main {% endcomment %}
     <!-- single car -->

                 
{% for car in object_list %}

{% comment %} views:{% get_hit_count for car %} <br> {% endcomment %}
     <div class="col-md-6 col-lg-4">
      <div class="card car-card shadow  mb-5 bg-body rounded">

        {% if car.carimages_set.all %}

        {% for vehicle_image in car.carimages_set.all %}
        {% if forloop.counter == 1 %}
        {% comment %} {% if vehicle_image.image %} {% endcomment %}
        <img src="{{vehicle_image.image.url}}" alt="{{vehicle_image.car.car_name|truncatechars:10}}" class="card-img-top car-img p-1" height="150">
        {% comment %} {% else %}
        no image ppppppppppppppppppppppppppppppppppppppppppppppppppp
        {% endif %} {% endcomment %}
        {%endif %}
        {% endfor %}

        {% else %}
        <img src="{% static '/img/car-3.png' %}" alt="{{car.car_name|truncatechars:10}}" class="card-img-top car-img p-1" height="150">

{% endif %}
        <!-- card body -->
        <div class="card-body ">
          <hr>
          <div class="car-info">
            
                <li class="fw-bold fs-5 py-1" style="list-style-type:none"> <a href="{{ car.get_absolute_url }}" class="text-reset text-decoration-none stretched-link">{{car.category }} {{car.car_name}}</a>  </li>
              
              
              <h6 class="py-1">kshs 
                <span class="text-muted">{{car.price |intcomma}}</span>
              </h6>
            
          </div>
          <div class=" d-flex justify-content-evenly flex-wrap">
            {% comment %} <div class="d-flex justify-content-around">...</div> {% endcomment %}
            
             <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.fuel}}</button>
             <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.transmission}}</button>
             <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.year_of_make}}</button>
             <button type="button" class="btn  m-1 p-1"style="background-color:beige">{{car.mileage |intcomma}} kms</button>
          </div>
         
        </div>
       
        <!-- end of card -->
        <div class="card-footer d-flex justify-content-around">
           <div class="btn-group">
          <a class="btn btn-warning w-100 " href="">View This Car</a>
       </div>
        </div>
      </div>
    </div>
    <!--end of single car -->
    {% empty %}
    <div class="card car-card">

      
      <div class="card-body shadow p-3 mb-5 bg-body rounded">
        <P class="text-center fw-bold fs-1 text-danger">Opps!!</P>
        <P class="text-center"> Sorry No Vehicles Are Available Today! </P>
      </div>
    </div>
{% endfor %}

            </div>

            {% if page_obj %} <!---- check if there are object for pagination-->
            <nav aria-label="Page navigation ">
              <ul class="pagination justify-content-end">
              {% if page_obj.has_previous %}
                  <li>
      {% comment %} <a  href="?page={{ page_obj.previous_page_number }}">        <span >&laquo;</span>      </a> {% endcomment %}
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>    
    {% endif %}

                  {% for i in page_obj.paginator.page_range %}
             {% if page_obj.number == i %}
             <li class="page-item active" aria-current="page"> <span class="page-link">{{i}}</span> </li>
                {% comment %} <li class="active"><a href="#">{{i}}</a></li> {% endcomment %}
                {% else %}
                  {% comment %} <li ><a href="?page={{i}}">{{i}}</a></li> {% endcomment %}
                  <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
              {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}          
              {% comment %} <li>    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>  </li>  {% endcomment %}
              <li class="page-item">                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>              </li>
  {% endif %}
              </ul>
            </nav>
              <br>
            

            {% endif %}

        </div>
<div class="col-md-3 col-sm-6">
  
  
        <section class="sidebar "> 
         
          <h3 class="sidebar-title text-center">Find Vehicle</h3>
          {% comment %} <div class="sidebar-item search-form">
        <form action="{% url 'find' %}" method="GET" >
           {% csrf_token %}
         
             <input type="search" name="q" >
           
             <button type="submit">search</button>
           
           </form>
           </div> {% endcomment %}
        {% comment %} <h3 class="sidebar-title">Search</h3>
          <div class="sidebar-item search-form">
        <form action="{% url 'find' %}" method="GET" >
           {% csrf_token %}
         
             <input type="search" name="q" >
           
             <button type="submit"><i class="bi bi-search"></i></button>
           
           </form>
           </div> {% endcomment %}
           <div class="card car-card shadow  mb-5 bg-body rounded ">
           <form class="home-search wow fadeInRight mx-2 p-2" action="{% url 'search' %}" method="GET"  data-wow-delay=".5s">
            {% csrf_token %}
          
          
          <div class="form-group mb-2">
            <label class="fw-bold text-dark">Vehicle</label>
            <div class="form-location">
            <input type="text"  name="car_name" class="form-control" placeholder="eg Fortuner...">
            </div>
            </div>
            <div class="form-group select-border mb-2">
              <label class="fw-bold text-dark">Model</label>
              <select class="form-control basic-select" name="category">
              <option value="0">All categories </option>
              {% for category in categories %}
              <option value="{{category.id}}">{{category.name}} </option>
              {% endfor %}
              </select>
              </div>
            <div class="form-group mb-2">
              <label class="fw-bold text-dark">Year Of Make</label>
              <div class="form-location">
              <input type="text"  name="year_of_make" class="form-control" placeholder="ef 2015...">
              </div>
              </div>
              <div class="form-group mb-2">
                <label class="fw-bold text-dark">Location</label>
                <div class="form-location">
                <input type="text"  name="location" class="form-control" placeholder="eg Starehe...">
                </div>
                </div>
        
          
          <div class="button text-center">
          <button class="btn btn-outline-dark"> Search </button>
          </div>
          </form>
        </div>
           <br>

           <h3 class="text-center">Popular Vehicles</h3>

           {% popular_vehicles as vehicles %}
           {% for vehicle in vehicles %}
           
 <div class="card car-card shadow  mb-1 bg-body rounded">
   <div class="card-body ">
     <div class="car-info">
       
           <li class="fw-bold fs-5 py-1" style="list-style-type:none"> <a href="{{vehicle.get_absolute_url}}" class="text-reset text-decoration-none stretched-link">{{vehicle.category}} {{vehicle.car_name}}</a>  </li>
         
         
         <h6 class="py-1">kshs 
           <span class="text-muted">{{vehicle.price |intcomma}}</span>
         </h6>
         <div class=" d-flex justify-content-evenly flex-wrap">
           {% comment %} <div class="d-flex justify-content-around">...</div> {% endcomment %}
           
            <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{vehicle.fuel}}</button>
            <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{vehicle.transmission}}</button>
            <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{vehicle.year_of_make}}</button>
            {% comment %} <button type="button" class="btn  m-1 p-1"style="background-color:beige">{{car.mileage}} kms</button> {% endcomment %}
         </div>
     </div>
    
    
   </div>
  
   <!-- end of card -->
  
 </div>
 {% empty %}
 
           <p class="text-muted" >No recent Vehicles</p>
 {% endfor %}

</section>
        </div>
        
    </div>
    </div>
</section>
</main>
{% endblock %}

templates/cars/edit_cars.html
{% extends 'base.html' %}
{% block title %} Edit Vehicles {% endblock %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
{% include 'includes/profile_message.html'%}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<section class="breadcrumbs">
    
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Edit Vehicle</h2>
      <ol>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'home' %}">Details</a></li>
        <li>Edit</li>
      </ol>
    </div>

  </div>
</section><!-- Job breadcrumbs Section -->

<h3 class="text-center py-3 fs-2">Edit</h3>
    <div class="d-flex justify-content-center fw-bold text-capitalize pb-5">
<div class="form-field col-9">
<form method="POST" enctype="multipart/form-data" id="car_edit">
    {% csrf_token %}
    {{ myform.media }}
    {% crispy form %}
    
    {% comment %} <div class="d-grid gap-2 col-6 mx-auto">
      
      <button class="btn btn-primary" >Submit</button>
    </div> {% endcomment %}
    </form>
  </div>
</div>
{% endblock %}

templates/cars/favourites.html
{% extends 'base.html' %}
{% block title %} Bookmarks {% endblock %}
{% block content %}
{% load static %}
{% load humanize %}
<main id="main"> 
    <br>
    
  
  <section class="breadcrumbs">
      
    <div class="container">
  
      <div class="d-flex justify-content-between align-items-center">
        <h2>Bookmarks</h2>
        <ol>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'cars' %}">Vehicles</a></li>
          <li>Bookmarks</li>
        </ol>
      </div>
  
    </div>
  </section><!-- Car breadcrumbs Section --> 
  <br>
  
<section class="vehicles" id="vehicles">
  <div class="container-fluid">
      <div class="row">

        <div class="col-md-12 col-sm-12">

          <div class="row">
         

  {% comment %} main {% endcomment %}
   <!-- single car -->

               
   {% for car in favourite_cars %}

{% comment %} views:{% get_hit_count for car %} <br> {% endcomment %}
   <div class="col-md-6 col-lg-3">
    <div class="card car-card shadow  mb-5 bg-body rounded">
      {% if car.carimages_set.all %} 

      {% for vehicle_image in car.carimages_set.all %}
      {% if forloop.counter == 1 %}
      <img src="{{vehicle_image.image.url}}" alt="{{vehicle_image.car.car_name|truncatechars:10}}" class="card-img-top car-img p-1" height="150">
      {%endif %}
      {% endfor %}
      {% else %}
      <img src="{% static '/img/car-3.png' %}" alt="{{car.car_name|truncatechars:10}}" class="card-img-top car-img p-1" height="150">

{% endif %}
      <!-- card body -->
      <div class="card-body ">
        <hr>
        <div class="car-info">
          
              <li class="fw-bold fs-5 py-1" style="list-style-type:none"> <a href="{{ car.get_absolute_url }}" class="text-reset text-decoration-none ">{{car.category }} {{car.car_name}}</a>  </li>
            
            
            <h6 class="py-1">kshs 
              <span class="text-muted">{{car.price |intcomma}}</span>
            </h6>
          
        </div>
        <div class=" d-flex justify-content-evenly flex-wrap">
          {% comment %} <div class="d-flex justify-content-around">...</div> {% endcomment %}
          
           <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.fuel}}</button>
           <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.transmission}}</button>
           {% comment %} <button type="button" class="btn  m-1 p-1" style="background-color:beige">{{car.body_type }}</button> {% endcomment %}
           <button type="button" class="btn  m-1 p-1"style="background-color:beige">{{car.mileage |intcomma}} kms</button>
        </div>
       
      </div>
     
      <!-- end of card -->
      <div class="card-footer d-flex justify-content-around">
         <div class="btn-group">
        <a class="btn btn-warning w-100 " href="{% url 'add_favourite' car.slug %}">Remove From Bookmarks</a>
        
       
     </div>
      </div>
    </div>
  </div>
  <!--end of single car -->
  {% empty %}
  <div class="card car-card">

    
    <div class="card-body shadow p-3 mb-5 bg-body rounded">
      <P class="text-center fw-bold fs-1 text-danger">Opps!!</P>
      <P class="text-center"> Sorry You Have No Bookmarks! </P>
    </div>
  </div>
{% endfor %}

          </div>

          {% if favourite_cars %} <!---- check if there are object for pagination-->
          <nav aria-label="Page navigation ">
            <ul class="pagination justify-content-end">
            {% if favourite_cars.has_previous %}
                <li>
          
          <a class="page-link" href="?page={{ favourite_cars.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
          </li>    
          {% endif %}
          
                {% for i in favourite_cars.paginator.page_range %}
           {% if favourite_cars.number == i %}
           <li class="page-item active" aria-current="page"> <span class="page-link">{{i}}</span> </li>
             
              {% else %}
              
                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            {% if favourite_cars.has_next %}          
          
            <li class="page-item"> <a class="page-link" href="?page={{ favourite_cars.next_page_number }}">Next</a>  </li>
          {% endif %}
            </ul>
            <br>
          
          
          {% endif %}

      </div>
<div class="col-md-3 col-sm-6">
      </div>
      
  </div>
  </div>
</section>
</main>



 {% endblock %}